name: manual-tag-test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag, e.g. 0.0.7'
        required: true

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create/update tag via API (with full error logging)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const tag   = `v${{ github.event.inputs.version }}`;
            const sha   = context.sha;

            async function logError(e) {
              core.info('--- error details begin ---');
              try { core.info(JSON.stringify(e, null, 2)); } catch {}
              if (e?.response?.data) {
                core.info('response.data: ' + JSON.stringify(e.response.data, null, 2));
              }
              core.info('--- error details end ---');
            }

            try {
              await github.rest.git.createRef({ owner, repo, ref: `refs/tags/${tag}`, sha });
              core.info(`Created tag ${tag} -> ${sha}`);
            } catch (e) {
              if (e.status === 422) {
                core.info(`Tag ${tag} exists; updating to ${sha}`);
                try {
                  await github.rest.git.updateRef({ owner, repo, ref: `tags/${tag}`, sha, force: true });
                  core.info(`Updated tag ${tag} -> ${sha}`);
                } catch (e2) {
                  core.setFailed(`Failed to update tag: ${e2.message}`);
                  await logError(e2);
                }
              } else {
                core.setFailed(`Failed to create tag: ${e.message}`);
                await logError(e);
              }
            }

      - name: Show remote tags (debug)
        run: |
          git fetch --tags --force
          echo "Last 10 tags on origin:"
          git ls-remote --tags origin | tail -n 10
