name: tag-repo-version
on:
  push:
    branches: [main]
    paths:
      - 'packages/repo-version/package.json'   # <— key change

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read repo version
        id: v
        run: echo "ver=$(jq -r .version packages/repo-version/package.json)" >> "$GITHUB_OUTPUT"

      - name: Create v tag if missing
        run: |
          TAG="v${{ steps.v.outputs.ver }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
          else
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi
